version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: payrollx_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: payrollx_main
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - payrollx-network

  redis:
    image: redis:7-alpine
    container_name: payrollx_redis
    ports:
      - "6379:6379"
    networks:
      - payrollx-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: payrollx_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpass
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - payrollx-network

  # solana:
  #   image: solanalabs/solana:v1.18
  #   container_name: payrollx_solana
  #   command: solana-test-validator --reset
  #   ports:
  #     - "8899:8899"
  #     - "8900:8900"
  #   networks:
  #     - payrollx-network

  mpc-server:
    build:
      context: ./apps/mpc-server
      dockerfile: Dockerfile
    container_name: payrollx_mpc
    environment:
      MPC_SERVER_HOST: 0.0.0.0
      MPC_SERVER_PORT: 8080
      MPC_JWT_SECRET: secret_key
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - payrollx-network

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: payrollx_api_gateway
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgresql://admin:adminpass@postgres:5432/payrollx_api
      RABBITMQ_URL: amqp://admin:adminpass@rabbitmq:5672
      JWT_SECRET: super_jwt_key
      REDIS_URL: redis://redis:6379
      AUTH_SERVICE_URL: http://auth-service:3001
      ORG_SERVICE_URL: http://org-service:3002
      EMPLOYEE_SERVICE_URL: http://employee-service:3003
      WALLET_SERVICE_URL: http://wallet-service:3005
      PAYROLL_SERVICE_URL: http://payroll-service:3006
      TRANSACTION_SERVICE_URL: http://transaction-service:3007
      NOTIFICATION_SERVICE_URL: http://notification-service:3008
      COMPLIANCE_SERVICE_URL: http://compliance-service:3009
    ports:
      - "3000:3000"
    networks:
      - payrollx-network

  # Core microservices (build using their existing Dockerfiles)
  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: payrollx_auth_service
    depends_on:
      - postgres
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://admin:adminpass@postgres:5432/payrollx_auth
      JWT_SECRET: super_jwt_key
      JWT_REFRESH_SECRET: super_refresh_key
      JWT_EXPIRES_IN: 1h
      JWT_REFRESH_EXPIRES_IN: 7d
    ports:
      - "3001:3001"
    networks:
      - payrollx-network

  org-service:
    build:
      context: .
      dockerfile: apps/org-service/Dockerfile
    container_name: payrollx_org_service
    depends_on:
      - postgres
    environment:
      PORT: 3002
      DATABASE_URL: postgresql://admin:adminpass@postgres:5432/payrollx_org
      JWT_SECRET: super_jwt_key
      SOLANA_CLUSTER: devnet
    ports:
      - "3002:3002"
    networks:
      - payrollx-network

  employee-service:
    build:
      context: .
      dockerfile: apps/employee-service/Dockerfile
    container_name: payrollx_employee_service
    depends_on:
      - postgres
    environment:
      PORT: 3003
      DATABASE_URL: postgresql://admin:adminpass@postgres:5432/payrollx_employee
      JWT_SECRET: super_jwt_key
    ports:
      - "3003:3003"
    networks:
      - payrollx-network

  wallet-service:
    build:
      context: .
      dockerfile: apps/wallet-service/Dockerfile
    container_name: payrollx_wallet_service
    depends_on:
      - postgres
      - mpc-server
    environment:
      PORT: 3005
      DATABASE_URL: postgresql://admin:adminpass@postgres:5432/payrollx_wallet
      JWT_SECRET: super_jwt_key
      MPC_SERVER_URL: http://mpc-server:8080
      MPC_JWT_SECRET: secret_key
      SOLANA_CLUSTER: devnet
    ports:
      - "3005:3005"
    networks:
      - payrollx-network

  payroll-service:
    build:
      context: .
      dockerfile: apps/payroll-service/Dockerfile
    container_name: payrollx_payroll_service
    depends_on:
      - postgres
      - rabbitmq
    environment:
      PORT: 3006
      DATABASE_URL: postgresql://admin:adminpass@postgres:5432/payrollx_payroll
      JWT_SECRET: super_jwt_key
      RABBITMQ_URL: amqp://admin:adminpass@rabbitmq:5672
      TRANSACTION_SERVICE_URL: http://transaction-service:3007
    ports:
      - "3006:3006"
    networks:
      - payrollx-network

  transaction-service:
    build:
      context: .
      dockerfile: apps/transaction-service/Dockerfile
    container_name: payrollx_transaction_service
    depends_on:
      - postgres
      - wallet-service
    environment:
      PORT: 3007
      DATABASE_URL: postgresql://admin:adminpass@postgres:5432/payrollx_transaction
      JWT_SECRET: super_jwt_key
      SOLANA_CLUSTER: devnet
      WALLET_SERVICE_URL: http://wallet-service:3005
    ports:
      - "3007:3007"
    networks:
      - payrollx-network

  notification-service:
    build:
      context: .
      dockerfile: apps/notification-service/Dockerfile
    container_name: payrollx_notification_service
    depends_on:
      - postgres
      - rabbitmq
    environment:
      PORT: 3008
      DATABASE_URL: postgresql://admin:adminpass@postgres:5432/payrollx_notification
      JWT_SECRET: super_jwt_key
      RABBITMQ_URL: amqp://admin:adminpass@rabbitmq:5672
    ports:
      - "3008:3008"
    networks:
      - payrollx-network

  compliance-service:
    build:
      context: .
      dockerfile: apps/compliance-service/Dockerfile
    container_name: payrollx_compliance_service
    depends_on:
      - postgres
      - rabbitmq
    environment:
      PORT: 3009
      DATABASE_URL: postgresql://admin:adminpass@postgres:5432/payrollx_compliance
      JWT_SECRET: super_jwt_key
      RABBITMQ_URL: amqp://admin:adminpass@rabbitmq:5672
    ports:
      - "3009:3009"
    networks:
      - payrollx-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: payrollx_web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
      NEXT_PUBLIC_SOLANA_RPC_URL: http://localhost:8899
      NEXT_PUBLIC_CLUSTER: devnet
    ports:
      - "3001:3000"
    depends_on:
      - api-gateway
    networks:
      - payrollx-network

networks:
  payrollx-network:
    driver: bridge

volumes:
  postgres_data:
