[package]
name = "mpc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-rt = "2"
actix-cors = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand = "0.8"
jsonwebtoken = "9"
env_logger = "0.11"
log = "0.4"
dotenv = "0.15"
uuid = { version = "1", features = ["v4", "serde"] }
base64 = "0.22"
sha2 = "0.10"
thiserror = "1"
chrono = { version = "0.4", features = ["serde"] }